### ISSUE TITLE
Data atual como centro da Timeline

### ISSUE THREAD

**Issue by everaldomatias** [brainwp/deolhonoplano-agenda#1]
Precisamos que o centro da timeline, ao abrir a página, seja a data atual, por exemplo:
16/05 • 16/06 • HOJE • 20/07 • 22/04

**Comment by claudiosanches** [comment]
Final de semana dou uma olhada nisso.

**Comment by claudiosanches** [comment]
Me tira desse issue ou fecha ele xD

**Comment by diegorojas** [comment]
Mals! hehe
